### PR TITLE
please read the txt file i sended!

### PR DESCRIPTION
**Pull request by Laknicek**
can u please read it geo!

### CODE REVIEW

**Review by cimok2000 — APPROVED** [review]
edited

**Comment by Laknicek** [comment]
the thing is i got insta banned when i asked the question, i didnt mean anything too!.

**Comment by Laknicek** [comment]
i will just wait for his response

**Comment by cimok2000** [comment]
Sounds like a plan, I'm taking a step back from everything now to focus on myself, I want to see where things go from here.

**Pull request closed without merging**
